version: "2"

services:
  # docker-compose -f dev/runtime.yml up
  ws:
    image: golang:1.11.4-alpine3.8
    command: go run main.go
    ports:
      - 9000:9000
    environment:
      - WS_PORT=9000
      - WS_PREFIX=/foo/
    volumes:
      - ..:/go/src/github.com/pottava/gorilla-websocket-chat
    working_dir: /go/src/github.com/pottava/gorilla-websocket-chat/server
    restart: always
    container_name: ws
